# Generated by Django 3.2.13 on 2022-07-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackapi.user',),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackapi.user',),
        ),
    ]
