# Generated by Django 3.2.13 on 2022-07-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0003_driverprofile_passengerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerprofile',
            name='passenger_id',
        ),
    ]
