# Generated by Django 4.0.6 on 2022-07-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0006_auto_20220721_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerrides',
            old_name='Price',
            new_name='price',
        ),
    ]
