# Generated by Django 4.0.6 on 2022-07-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0007_rename_price_passengerrides_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoDriver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackapi.user',),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('TRANSFER', 'Transfer'), ('WALLET', 'Wallet')], max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PASSENGER', 'Passenger'), ('DRIVER', 'Driver'), ('CODRIVER', 'CoDriver')], max_length=25),
        ),
        migrations.CreateModel(
            name='CoDriverRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('start_location', models.TextField()),
                ('destination', models.TextField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='trackapi.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapi.codriver')),
            ],
        ),
        migrations.CreateModel(
            name='CoDriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('verifyID', models.BinaryField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('current_location', models.TextField(blank=True)),
                ('destination', models.TextField(blank=True)),
                ('in_trip', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackapi.codriver')),
            ],
        ),
        migrations.AddField(
            model_name='driverrides',
            name='co_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver', to='trackapi.codriver'),
        ),
    ]
