# Generated by Django 4.0.6 on 2022-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0008_codriver_passengerprofile_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
