# Generated by Django 4.0.6 on 2022-07-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0009_driverprofile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerrides',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
