# Generated by Django 4.0.6 on 2022-07-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0010_alter_passengerrides_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrides',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('PROGRESS', 'Progress'), ('COMPLETED', 'Completed')], default='PROGRESS', max_length=128),
        ),
    ]
