# Generated by Django 4.0.6 on 2022-07-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0011_passengerrides_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrides',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_driver', to='trackapi.driver'),
        ),
    ]
