# Generated by Django 4.0.6 on 2022-07-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0012_passengerrides_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrides',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('TRANSFER', 'Transfer'), ('WALLET', 'Wallet')], max_length=128),
        ),
        migrations.AlterField(
            model_name='passengerrides',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('PROGRESS', 'Progress'), ('COMPLETED', 'Completed'), ('REQUESTED', 'Requested')], default='REQUESTED', max_length=128),
        ),
    ]
