# Generated by Django 4.0.6 on 2022-07-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0014_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_location', models.CharField(max_length=128)),
                ('destination_location', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='trackapi.vehicle'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='trackapi.route'),
        ),
    ]
