# Generated by Django 4.0.6 on 2022-07-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0016_remove_vehicle_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
    ]
