# Generated by Django 4.0.6 on 2022-07-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0023_alter_driverprofile_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='journey',
            field=models.ManyToManyField(blank=True, null=True, related_name='route', to='trackapi.route'),
        ),
    ]
