# Generated by Django 4.0.6 on 2022-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0027_alter_driverprofile_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='passengers',
            field=models.IntegerField(default=0),
        ),
    ]
