# Generated by Django 4.0.6 on 2022-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0028_driverprofile_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
