# Generated by Django 4.0.6 on 2022-07-25 12:47

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0029_route_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='journey',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='journey', to='trackapi.route'),
        ),
    ]
