# Generated by Django 4.0.6 on 2022-07-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0031_alter_passengerrides_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='present_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_location', to='trackapi.route'),
        ),
    ]
